version: '3.8'
services:
  redis:
    image: 'redis:latest'
    ports:
      - "127.0.0.1:6378:6379"

  rdbms:
    image: 'postgres:17'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'panacea'
    ports:
      - "127.0.0.1:5433:5432"